// Fill-in-Verse Question Bank
// Format: { b: "Beginning...", blank: "missing word", a: "...end", r: "Reference", o: ["option1", "option2", "option3", "option4"] }

const VERSE_Q = [
  {"b": "In the beginning God created the ", "blank": "heavens", "a": " and the earth.", "r": "Genesis 1:1", "o": ["heavens", "stars", "oceans", "mountains"]},
  {"b": "For God so loved the ", "blank": "world", "a": ", that he gave his only begotten Son.", "r": "John 3:16", "o": ["world", "church", "people", "nations"]},
  {"b": "The Lord is my ", "blank": "shepherd", "a": "; I shall not want.", "r": "Psalm 23:1", "o": ["shepherd", "king", "father", "refuge"]},
  {"b": "I can do all things through ", "blank": "Christ", "a": " who strengthens me.", "r": "Philippians 4:13", "o": ["Christ", "faith", "prayer", "God"]},
  {"b": "Trust in the Lord with all your ", "blank": "heart", "a": ", and lean not on your own understanding.", "r": "Proverbs 3:5", "o": ["heart", "mind", "soul", "strength"]},
  {"b": "In all your ways ", "blank": "acknowledge", "a": " Him, and He shall direct your paths.", "r": "Proverbs 3:6", "o": ["acknowledge", "worship", "praise", "seek"]},
  {"b": "But seek first the ", "blank": "kingdom", "a": " of God and His righteousness.", "r": "Matthew 6:33", "o": ["kingdom", "glory", "will", "face"]},
  {"b": "Jesus said to him, 'I am the ", "blank": "way", "a": ", the truth, and the life.'", "r": "John 14:6", "o": ["way", "door", "light", "vine"]},
  {"b": "For all have ", "blank": "sinned", "a": " and fall short of the glory of God.", "r": "Romans 3:23", "o": ["sinned", "erred", "failed", "doubted"]},
  {"b": "For the wages of sin is ", "blank": "death", "a": ", but the gift of God is eternal life.", "r": "Romans 6:23", "o": ["death", "sorrow", "pain", "judgment"]},
  {"b": "But God demonstrates His own ", "blank": "love", "a": " toward us, in that while we were still sinners, Christ died for us.", "r": "Romans 5:8", "o": ["love", "grace", "mercy", "power"]},
  {"b": "And we know that all things work together for ", "blank": "good", "a": " to those who love God.", "r": "Romans 8:28", "o": ["good", "blessing", "glory", "peace"]},
  {"b": "If God is for us, who can be ", "blank": "against", "a": " us?", "r": "Romans 8:31", "o": ["against", "defeat", "harm", "judge"]},
  {"b": "Faith is the ", "blank": "substance", "a": " of things hoped for, the evidence of things not seen.", "r": "Hebrews 11:1", "o": ["substance", "feeling", "belief", "thought"]},
  {"b": "But without ", "blank": "faith", "a": " it is impossible to please Him.", "r": "Hebrews 11:6", "o": ["faith", "works", "prayer", "love"]},
  {"b": "The grass withers, the flower fades, but the ", "blank": "word", "a": " of our God stands forever.", "r": "Isaiah 40:8", "o": ["word", "spirit", "name", "glory"]},
  {"b": "For I know the ", "blank": "plans", "a": " I have for you, declares the Lord.", "r": "Jeremiah 29:11", "o": ["plans", "thoughts", "paths", "ways"]},
  {"b": "Be ", "blank": "still", "a": ", and know that I am God.", "r": "Psalm 46:10", "o": ["still", "quiet", "strong", "patient"]},
  {"b": "Your word is a ", "blank": "lamp", "a": " to my feet and a light to my path.", "r": "Psalm 119:105", "o": ["lamp", "guide", "shield", "sun"]},
  {"b": "I am the Alpha and the ", "blank": "Omega", "a": ", the Beginning and the End.", "r": "Revelation 1:8", "o": ["Omega", "Zion", "Glory", "Peace"]},
  {"b": "Let everything that has ", "blank": "breath", "a": " praise the Lord.", "r": "Psalm 150:6", "o": ["breath", "life", "voice", "soul"]},
  {"b": "Create in me a clean ", "blank": "heart", "a": ", O God, and renew a steadfast spirit within me.", "r": "Psalm 51:10", "o": ["heart", "mind", "spirit", "soul"]},
  {"b": "Give thanks to the Lord, for He is ", "blank": "good", "a": "; His love endures forever.", "r": "Psalm 107:1", "o": ["good", "great", "holy", "mighty"]},
  {"b": "This is the day the Lord has made; let us ", "blank": "rejoice", "a": " and be glad in it.", "r": "Psalm 118:24", "o": ["rejoice", "sing", "dance", "praise"]},
  {"b": "A ", "blank": "gentle", "a": " answer turns away wrath, but a harsh word stirs up anger.", "r": "Proverbs 15:1", "o": ["gentle", "kind", "soft", "wise"]},
  {"b": "Iron sharpens iron, and one man ", "blank": "sharpens", "a": " another.", "r": "Proverbs 27:17", "o": ["sharpens", "helps", "teaches", "builds"]},
  {"b": "The fear of the Lord is the beginning of ", "blank": "wisdom", "a": ".", "r": "Proverbs 9:10", "o": ["wisdom", "knowledge", "faith", "life"]},
  {"b": "As for me and my house, we will serve the ", "blank": "Lord", "a": ".", "r": "Joshua 24:15", "o": ["Lord", "King", "God", "Creator"]},
  {"b": "Be strong and ", "blank": "courageous", "a": ". Do not be afraid; do not be discouraged.", "r": "Joshua 1:9", "o": ["courageous", "brave", "bold", "fearless"]},
  {"b": "He gives ", "blank": "strength", "a": " to the weary and increases the power of the weak.", "r": "Isaiah 40:29", "o": ["strength", "peace", "rest", "hope"]},
  {"b": "But those who hope in the Lord will renew their ", "blank": "strength", "a": ".", "r": "Isaiah 40:31", "o": ["strength", "youth", "faith", "days"]},
  {"b": "They will soar on wings like ", "blank": "eagles", "a": "; they will run and not grow weary.", "r": "Isaiah 40:31", "o": ["eagles", "hawks", "doves", "angels"]},
  {"b": "Fear not, for I am with you; be not dismayed, for I am your ", "blank": "God", "a": ".", "r": "Isaiah 41:10", "o": ["God", "Lord", "King", "Father"]},
  {"b": "I have hidden your word in my ", "blank": "heart", "a": " that I might not sin against you.", "r": "Psalm 119:11", "o": ["heart", "mind", "soul", "memory"]},
  {"b": "The name of the Lord is a strong ", "blank": "tower", "a": "; the righteous run to it and are safe.", "r": "Proverbs 18:10", "o": ["tower", "fortress", "shield", "rock"]},
  {"b": "Commit your way to the Lord; trust in him and he will ", "blank": "act", "a": ".", "r": "Psalm 37:5", "o": ["act", "save", "help", "guide"]},
  {"b": "For my thoughts are not your thoughts, neither are your ways my ", "blank": "ways", "a": ", declares the Lord.", "r": "Isaiah 55:8", "o": ["ways", "plans", "paths", "ideas"]},
  {"b": "Call to me and I will answer you and tell you ", "blank": "great", "a": " and unsearchable things.", "r": "Jeremiah 33:3", "o": ["great", "mighty", "hidden", "holy"]},
  {"b": "The steadfast love of the Lord never ", "blank": "ceases", "a": "; his mercies never come to an end.", "r": "Lamentations 3:22", "o": ["ceases", "fails", "ends", "stops"]},
  {"b": "His mercies are new every ", "blank": "morning", "a": "; great is your faithfulness.", "r": "Lamentations 3:23", "o": ["morning", "day", "hour", "evening"]},
  {"b": "He has shown you, O mortal, what is good. And what does the Lord ", "blank": "require", "a": " of you?", "r": "Micah 6:8", "o": ["require", "ask", "want", "seek"]},
  {"b": "To act justly and to love ", "blank": "mercy", "a": " and to walk humbly with your God.", "r": "Micah 6:8", "o": ["mercy", "kindness", "peace", "grace"]},
  {"b": "The Lord your God is with you, the Mighty Warrior who ", "blank": "saves", "a": ".", "r": "Zephaniah 3:17", "o": ["saves", "fights", "helps", "leads"]},
  {"b": "Blessed are the ", "blank": "poor", "a": " in spirit, for theirs is the kingdom of heaven.", "r": "Matthew 5:3", "o": ["poor", "meek", "pure", "humble"]},
  {"b": "Blessed are the ", "blank": "peacemakers", "a": ", for they will be called children of God.", "r": "Matthew 5:9", "o": ["peacemakers", "merciful", "humble", "righteous"]},
  {"b": "You are the ", "blank": "light", "a": " of the world. A town built on a hill cannot be hidden.", "r": "Matthew 5:14", "o": ["light", "salt", "hope", "love"]},
  {"b": "In the same way, let your light ", "blank": "shine", "a": " before others.", "r": "Matthew 5:16", "o": ["shine", "glow", "burn", "appear"]},
  {"b": "Love your ", "blank": "enemies", "a": " and pray for those who persecute you.", "r": "Matthew 5:44", "o": ["enemies", "neighbors", "friends", "brothers"]},
  {"b": "Our Father in heaven, ", "blank": "hallowed", "a": " be your name.", "r": "Matthew 6:9", "o": ["hallowed", "holy", "great", "blessed"]},
  {"b": "Give us today our daily ", "blank": "bread", "a": ".", "r": "Matthew 6:11", "o": ["bread", "food", "needs", "portion"]},
  {"b": "Do not worry about ", "blank": "tomorrow", "a": ", for tomorrow will worry about itself.", "r": "Matthew 6:34", "o": ["tomorrow", "life", "food", "money"]},
  {"b": "Ask and it will be given to you; ", "blank": "seek", "a": " and you will find.", "r": "Matthew 7:7", "o": ["seek", "knock", "look", "wait"]},
  {"b": "So in everything, do to others what you would have them ", "blank": "do", "a": " to you.", "r": "Matthew 7:12", "o": ["do", "say", "give", "think"]},
  {"b": "Come to me, all you who are weary and burdened, and I will give you ", "blank": "rest", "a": ".", "r": "Matthew 11:28", "o": ["rest", "peace", "strength", "hope"]},
  {"b": "For where two or three ", "blank": "gather", "a": " in my name, there am I with them.", "r": "Matthew 18:20", "o": ["gather", "pray", "meet", "speak"]},
  {"b": "With man this is impossible, but with God ", "blank": "all", "a": " things are possible.", "r": "Matthew 19:26", "o": ["all", "many", "some", "great"]},
  {"b": "Go therefore and make ", "blank": "disciples", "a": " of all nations.", "r": "Matthew 28:19", "o": ["disciples", "followers", "believers", "friends"]},
  {"b": "And surely I am with you ", "blank": "always", "a": ", to the very end of the age.", "r": "Matthew 28:20", "o": ["always", "forever", "daily", "truly"]},
  {"b": "For even the Son of Man did not come to be served, but to ", "blank": "serve", "a": ".", "r": "Mark 10:45", "o": ["serve", "rule", "teach", "save"]},
  {"b": "For nothing will be ", "blank": "impossible", "a": " with God.", "r": "Luke 1:37", "o": ["impossible", "difficult", "hard", "unknown"]},
  {"b": "Glory to God in the highest heaven, and on earth ", "blank": "peace", "a": " to those on whom his favor rests.", "r": "Luke 2:14", "o": ["peace", "joy", "goodwill", "love"]},
  {"b": "In the beginning was the ", "blank": "Word", "a": ", and the Word was with God, and the Word was God.", "r": "John 1:1", "o": ["Word", "Light", "Son", "Spirit"]},
  {"b": "The Word became ", "blank": "flesh", "a": " and made his dwelling among us.", "r": "John 1:14", "o": ["flesh", "man", "human", "light"]},
  {"b": "For God did not send his Son into the world to ", "blank": "condemn", "a": " the world.", "r": "John 3:17", "o": ["condemn", "judge", "punish", "rule"]},
  {"b": "I am the light of the world. Whoever follows me will never walk in ", "blank": "darkness", "a": ".", "r": "John 8:12", "o": ["darkness", "sin", "error", "fear"]},
  {"b": "Then you will know the truth, and the truth will set you ", "blank": "free", "a": ".", "r": "John 8:32", "o": ["free", "apart", "whole", "right"]},
  {"b": "The thief comes only to steal and kill and destroy; I have come that they may have ", "blank": "life", "a": ".", "r": "John 10:10", "o": ["life", "joy", "peace", "hope"]},
  {"b": "I am the good ", "blank": "shepherd", "a": ". The good shepherd lays down his life for the sheep.", "r": "John 10:11", "o": ["shepherd", "leader", "master", "king"]},
  {"b": "I am the ", "blank": "resurrection", "a": " and the life. The one who believes in me will live.", "r": "John 11:25", "o": ["resurrection", "way", "truth", "light"]},
  {"b": "By this everyone will know that you are my disciples, if you ", "blank": "love", "a": " one another.", "r": "John 13:35", "o": ["love", "serve", "help", "know"]},
  {"b": "Do not let your hearts be ", "blank": "troubled", "a": ". You believe in God; believe also in me.", "r": "John 14:1", "o": ["troubled", "afraid", "heavy", "broken"]},
  {"b": "If you love me, ", "blank": "keep", "a": " my commands.", "r": "John 14:15", "o": ["keep", "obey", "follow", "know"]},
  {"b": "Peace I leave with you; my peace I ", "blank": "give", "a": " you.", "r": "John 14:27", "o": ["give", "offer", "send", "bring"]},
  {"b": "I am the ", "blank": "vine", "a": "; you are the branches.", "r": "John 15:5", "o": ["vine", "root", "tree", "stem"]},
  {"b": "Greater love has no one than this: to lay down one's ", "blank": "life", "a": " for one's friends.", "r": "John 15:13", "o": ["life", "soul", "all", "heart"]},
  {"b": "In this world you will have trouble. But take heart! I have ", "blank": "overcome", "a": " the world.", "r": "John 16:33", "o": ["overcome", "conquered", "won", "defeated"]},
  {"b": "Sanctify them by the truth; your word is ", "blank": "truth", "a": ".", "r": "John 17:17", "o": ["truth", "holy", "life", "light"]},
  {"b": "But you will receive ", "blank": "power", "a": " when the Holy Spirit comes on you.", "r": "Acts 1:8", "o": ["power", "strength", "wisdom", "grace"]},
  {"b": "Salvation is found in no one else, for there is no other ", "blank": "name", "a": " under heaven given to mankind.", "r": "Acts 4:12", "o": ["name", "way", "path", "god"]},
  {"b": "Believe in the Lord Jesus, and you will be ", "blank": "saved", "a": ".", "r": "Acts 16:31", "o": ["saved", "blessed", "healed", "chosen"]},
  {"b": "It is more blessed to ", "blank": "give", "a": " than to receive.", "r": "Acts 20:35", "o": ["give", "serve", "love", "work"]},
  {"b": "For I am not ashamed of the ", "blank": "gospel", "a": ", because it is the power of God that brings salvation.", "r": "Romans 1:16", "o": ["gospel", "word", "truth", "cross"]},
  {"b": "Faith comes from ", "blank": "hearing", "a": " the message.", "r": "Romans 10:17", "o": ["hearing", "reading", "sharing", "praying"]},
  {"b": "Therefore, I urge you, brothers and sisters, in view of God's mercy, to offer your bodies as a living ", "blank": "sacrifice", "a": ".", "r": "Romans 12:1", "o": ["sacrifice", "offering", "vessel", "temple"]},
  {"b": "Do not conform to the pattern of this world, but be ", "blank": "transformed", "a": " by the renewing of your mind.", "r": "Romans 12:2", "o": ["transformed", "changed", "renewed", "guided"]},
  {"b": "Be joyful in hope, patient in ", "blank": "affliction", "a": ", faithful in prayer.", "r": "Romans 12:12", "o": ["affliction", "trouble", "suffering", "trials"]},
  {"b": "Do not be overcome by evil, but overcome evil with ", "blank": "good", "a": ".", "r": "Romans 12:21", "o": ["good", "love", "kindness", "faith"]},
  {"b": "For the message of the cross is ", "blank": "foolishness", "a": " to those who are perishing.", "r": "1 Corinthians 1:18", "o": ["foolishness", "weakness", "scandal", "mystery"]},
  {"b": "Do you not know that your bodies are ", "blank": "temples", "a": " of the Holy Spirit?", "r": "1 Corinthians 6:19", "o": ["temples", "houses", "vessels", "servants"]},
  {"b": "No temptation has overtaken you except what is ", "blank": "common", "a": " to mankind.", "r": "1 Corinthians 10:13", "o": ["common", "usual", "normal", "known"]},
  {"b": "God is ", "blank": "faithful", "a": ", and he will not let you be tempted beyond what you can bear.", "r": "1 Corinthians 10:13", "o": ["faithful", "good", "just", "strong"]},
  {"b": "Love is ", "blank": "patient", "a": ", love is kind. It does not envy, it does not boast.", "r": "1 Corinthians 13:4", "o": ["patient", "gentle", "humble", "quiet"]},
  {"b": "Love never ", "blank": "fails", "a": ".", "r": "1 Corinthians 13:8", "o": ["fails", "ends", "stops", "ceases"]},
  {"b": "And now these three remain: faith, hope and love. But the greatest of these is ", "blank": "love", "a": ".", "r": "1 Corinthians 13:13", "o": ["love", "faith", "hope", "grace"]},
  {"b": "Be on your guard; stand firm in the ", "blank": "faith", "a": "; be courageous; be strong.", "r": "1 Corinthians 16:13", "o": ["faith", "Lord", "truth", "word"]},
  {"b": "Do everything in ", "blank": "love", "a": ".", "r": "1 Corinthians 16:14", "o": ["love", "faith", "peace", "joy"]},
  {"b": "For we walk by ", "blank": "faith", "a": ", not by sight.", "r": "2 Corinthians 5:7", "o": ["faith", "spirit", "truth", "hope"]},
  {"b": "Therefore, if anyone is in Christ, the new ", "blank": "creation", "a": " has come.", "r": "2 Corinthians 5:17", "o": ["creation", "nature", "man", "life"]},
  {"b": "My ", "blank": "grace", "a": " is sufficient for you, for my power is made perfect in weakness.", "r": "2 Corinthians 12:9", "o": ["grace", "mercy", "love", "peace"]},
  {"b": "I have been crucified with Christ and I no longer ", "blank": "live", "a": ", but Christ lives in me.", "r": "Galatians 2:20", "o": ["live", "work", "suffer", "walk"]},
  {"b": "But the fruit of the Spirit is love, joy, peace, ", "blank": "forbearance", "a": ", kindness, goodness, faithfulness.", "r": "Galatians 5:22", "o": ["forbearance", "patience", "longsuffering", "hope"]},
  {"b": "Gentleness and self-control. Against such things there is no ", "blank": "law", "a": ".", "r": "Galatians 5:23", "o": ["law", "limit", "judgment", "charge"]},
  {"b": "A man reaps what he ", "blank": "sows", "a": ".", "r": "Galatians 6:7", "o": ["sows", "plants", "does", "says"]},
  {"b": "Let us not become weary in doing ", "blank": "good", "a": ".", "r": "Galatians 6:9", "o": ["good", "well", "work", "right"]},
  {"b": "For it is by ", "blank": "grace", "a": " you have been saved, through faith.", "r": "Ephesians 2:8", "o": ["grace", "mercy", "works", "belief"]},
  {"b": "It is not from ", "blank": "yourselves", "a": ", it is the gift of God.", "r": "Ephesians 2:8", "o": ["yourselves", "works", "effort", "man"]},
  {"b": "For we are God’s ", "blank": "handiwork", "a": ", created in Christ Jesus to do good works.", "r": "Ephesians 2:10", "o": ["handiwork", "masterpiece", "creation", "servants"]},
  {"b": "Now to him who is able to do immeasurably ", "blank": "more", "a": " than all we ask or imagine.", "r": "Ephesians 3:20", "o": ["more", "above", "beyond", "greater"]},
  {"b": "Be kind and compassionate to one another, ", "blank": "forgiving", "a": " each other.", "r": "Ephesians 4:32", "o": ["forgiving", "loving", "helping", "serving"]},
  {"b": "Put on the full ", "blank": "armor", "a": " of God, so that you can take your stand.", "r": "Ephesians 6:11", "o": ["armor", "shield", "clothing", "strength"]},
  {"b": "For our struggle is not against ", "blank": "flesh", "a": " and blood.", "r": "Ephesians 6:12", "o": ["flesh", "man", "people", "earth"]},
  {"b": "Being confident of this, that he who began a good work in you will carry it on to ", "blank": "completion", "a": ".", "r": "Philippians 1:6", "o": ["completion", "finish", "perfection", "end"]},
  {"b": "For to me, to live is Christ and to die is ", "blank": "gain", "a": ".", "r": "Philippians 1:21", "o": ["gain", "loss", "victory", "better"]},
  {"b": "Rejoice in the Lord ", "blank": "always", "a": ". I will say it again: Rejoice!", "r": "Philippians 4:4", "o": ["always", "daily", "now", "forever"]},
  {"b": "Do not be ", "blank": "anxious", "a": " about anything, but in every situation, by prayer and petition.", "r": "Philippians 4:6", "o": ["anxious", "worried", "afraid", "careful"]},
  {"b": "And the peace of God, which transcends all ", "blank": "understanding", "a": ", will guard your hearts.", "r": "Philippians 4:7", "o": ["understanding", "wisdom", "knowledge", "thought"]},
  {"b": "Whatever is ", "blank": "true", "a": ", whatever is noble, whatever is right, think about such things.", "r": "Philippians 4:8", "o": ["true", "good", "holy", "pure"]},
  {"b": "And my God will meet all your ", "blank": "needs", "a": " according to the riches of his glory.", "r": "Philippians 4:19", "o": ["needs", "wants", "desires", "requests"]},
  {"b": "Set your minds on things ", "blank": "above", "a": ", not on earthly things.", "r": "Colossians 3:2", "o": ["above", "heavenly", "holy", "spiritual"]},
  {"b": "And over all these virtues put on ", "blank": "love", "a": ", which binds them all together in perfect unity.", "r": "Colossians 3:14", "o": ["love", "peace", "grace", "faith"]},
  {"b": "Whatever you do, work at it with all your ", "blank": "heart", "a": ", as working for the Lord.", "r": "Colossians 3:23", "o": ["heart", "might", "strength", "soul"]},
  {"b": "Rejoice always, pray ", "blank": "continually", "a": ", give thanks in all circumstances.", "r": "1 Thessalonians 5:16-18", "o": ["continually", "without ceasing", "daily", "often"]},
  {"b": "Don't let anyone look down on you because you are ", "blank": "young", "a": ".", "r": "1 Timothy 4:12", "o": ["young", "small", "weak", "new"]},
  {"b": "For the love of money is a root of all kinds of ", "blank": "evil", "a": ".", "r": "1 Timothy 6:10", "o": ["evil", "trouble", "sin", "sorrow"]},
  {"b": "Fight the good fight of the ", "blank": "faith", "a": ".", "r": "1 Timothy 6:12", "o": ["faith", "truth", "Lord", "gospel"]},
  {"b": "For the Spirit God gave us does not make us ", "blank": "timid", "a": ", but gives us power.", "r": "2 Timothy 1:7", "o": ["timid", "afraid", "weak", "shameful"]},
  {"b": "All ", "blank": "Scripture", "a": " is God-breathed and is useful for teaching.", "r": "2 Timothy 3:16", "o": ["Scripture", "Bible", "Word", "Wisdom"]},
  {"b": "I have fought the good fight, I have finished the ", "blank": "race", "a": ", I have kept the faith.", "r": "2 Timothy 4:7", "o": ["race", "course", "work", "path"]},
  {"b": "For the word of God is ", "blank": "alive", "a": " and active. Sharper than any double-edged sword.", "r": "Hebrews 4:12", "o": ["alive", "living", "quick", "powerful"]},
  {"b": "Let us then approach God’s throne of ", "blank": "grace", "a": " with confidence.", "r": "Hebrews 4:16", "o": ["grace", "mercy", "glory", "power"]},
  {"b": "Never will I leave you; never will I ", "blank": "forsake", "a": " you.", "r": "Hebrews 13:5", "o": ["forsake", "abandon", "forget", "fail"]},
  {"b": "Jesus Christ is the ", "blank": "same", "a": " yesterday and today and forever.", "r": "Hebrews 13:8", "o": ["same", "Lord", "King", "God"]},
  {"b": "Consider it pure ", "blank": "joy", "a": ", my brothers and sisters, whenever you face trials.", "r": "James 1:2", "o": ["joy", "peace", "blessing", "gain"]},
  {"b": "If any of you lacks ", "blank": "wisdom", "a": ", you should ask God.", "r": "James 1:5", "o": ["wisdom", "faith", "strength", "guidance"]},
  {"b": "Everyone should be quick to listen, slow to ", "blank": "speak", "a": " and slow to become angry.", "r": "James 1:19", "o": ["speak", "talk", "answer", "judge"]},
  {"b": "Do not merely listen to the word, and so deceive yourselves. ", "blank": "Do", "a": " what it says.", "r": "James 1:22", "o": ["Do", "Obey", "Practice", "Follow"]},
  {"b": "Submit yourselves, then, to God. Resist the ", "blank": "devil", "a": ", and he will flee from you.", "r": "James 4:7", "o": ["devil", "enemy", "evil", "temptation"]},
  {"b": "Come ", "blank": "near", "a": " to God and he will come near to you.", "r": "James 4:8", "o": ["near", "close", "back", "humble"]},
  {"b": "Humble yourselves before the Lord, and he will ", "blank": "lift", "a": " you up.", "r": "James 4:10", "o": ["lift", "raise", "exalt", "honor"]},
  {"b": "The prayer of a righteous person is powerful and ", "blank": "effective", "a": ".", "r": "James 5:16", "o": ["effective", "availing", "good", "heard"]},
  {"b": "Cast all your ", "blank": "anxiety", "a": " on him because he cares for you.", "r": "1 Peter 5:7", "o": ["anxiety", "care", "worry", "burden"]},
  {"b": "Be alert and of sober mind. Your enemy the devil prowls around like a roaring ", "blank": "lion", "a": ".", "r": "1 Peter 5:8", "o": ["lion", "beast", "wolf", "spirit"]},
  {"b": "If we ", "blank": "confess", "a": " our sins, he is faithful and just and will forgive us.", "r": "1 John 1:9", "o": ["confess", "admit", "repent of", "reveal"]},
  {"b": "See what great love the Father has lavished on us, that we should be called ", "blank": "children", "a": " of God!", "r": "1 John 3:1", "o": ["children", "sons", "servants", "people"]},
  {"b": "Dear children, let us not love with words or speech but with actions and in ", "blank": "truth", "a": ".", "r": "1 John 3:18", "o": ["truth", "deed", "power", "spirit"]},
  {"b": "Whoever does not love does not know God, because God is ", "blank": "love", "a": ".", "r": "1 John 4:8", "o": ["love", "light", "holy", "good"]},
  {"b": "There is no ", "blank": "fear", "a": " in love. But perfect love drives out fear.", "r": "1 John 4:18", "o": ["fear", "doubt", "sin", "hate"]},
  {"b": "We love because he first ", "blank": "loved", "a": " us.", "r": "1 John 4:19", "o": ["loved", "knew", "chose", "saved"]},
  {"b": "Here I am! I stand at the ", "blank": "door", "a": " and knock.", "r": "Revelation 3:20", "o": ["door", "gate", "entrance", "heart"]},
  {"b": "He will wipe every ", "blank": "tear", "a": " from their eyes.", "r": "Revelation 21:4", "o": ["tear", "sorrow", "pain", "stain"]},
  {"b": "Look, I am coming ", "blank": "soon", "a": "!", "r": "Revelation 22:7", "o": ["soon", "quickly", "back", "again"]},
  {"b": "The grace of the Lord Jesus be with God's people. ", "blank": "Amen", "a": ".", "r": "Revelation 22:21", "o": ["Amen", "Truly", "Forever", "Always"]}
];
